$root = "C:\Users\Archi\skylux-airways"
$populateFile = Join-Path $root "src\scripts\populate.ts"
$portalFile = Join-Path $root "src\app\(customer)\portal\page.tsx"
$NL = [Environment]::NewLine
$mi = @("    // Michigan (USA)","    DTW: {city:""Detroit"",country:""United States"",airport:""Detroit Metropolitan Wayne County"",terminal:""MN""},","    MQT: {city:""Marquette"",country:""United States"",airport:""Sawyer International"",terminal:""T1""},","    GRR: {city:""Grand Rapids"",country:""United States"",airport:""Gerald R. Ford International"",terminal:""T1""},","    FNT: {city:""Flint"",country:""United States"",airport:""Bishop International"",terminal:""T1""},","    LAN: {city:""Lansing"",country:""United States"",airport:""Capital Region International"",terminal:""T1""},","    MBS: {city:""Saginaw"",country:""United States"",airport:""MBS International"",terminal:""T1""},","    AZO: {city:""Kalamazoo"",country:""United States"",airport:""Kalamazoo Battle Creek International"",terminal:""T1""},","    TVC: {city:""Traverse City"",country:""United States"",airport:""Cherry Capital"",terminal:""T1""},","    PLN: {city:""Pellston"",country:""United States"",airport:""Pellston Regional"",terminal:""T1""},","    CIU: {city:""Sault Ste. Marie"",country:""United States"",airport:""Chippewa County International"",terminal:""T1""},","    ESC: {city:""Escanaba"",country:""United States"",airport:""Delta County"",terminal:""T1""},","    IMT: {city:""Iron Mountain"",country:""United States"",airport:""Ford Airport"",terminal:""T1""},","    APN: {city:""Alpena"",country:""United States"",airport:""Alpena County Regional"",terminal:""T1""},","    CMX: {city:""Hancock"",country:""United States"",airport:""Houghton County Memorial"",terminal:""T1""},","    IWD: {city:""Ironwood"",country:""United States"",airport:""Gogebic-Iron County"",terminal:""T1""},","    MBL: {city:""Manistee"",country:""United States"",airport:""Manistee County Blacker"",terminal:""T1""},")
$block = $NL + ($mi -join $NL)
$c = Get-Content $populateFile -Raw
if ($c -match "MQT") { Write-Host "[SKIP] Already in populate.ts" -ForegroundColor Yellow } else { $m = [regex]::Match($c, 'BOS:\s*\{[^}]+\},?'); if ($m.Success) { $c = $c.Insert($m.Index + $m.Length, $block); [System.IO.File]::WriteAllText($populateFile, $c); Write-Host "[OK] Michigan added to populate.ts" -ForegroundColor Green } else { Write-Host "[WARN] BOS not found" -ForegroundColor Red } }
$pi = @("  // Michigan","  {code:""DTW"",city:""Detroit"",name:""Detroit Metro"",country:""USA""},","  {code:""MQT"",city:""Marquette"",name:""Sawyer International"",country:""USA""},","  {code:""GRR"",city:""Grand Rapids"",name:""Gerald R. Ford"",country:""USA""},","  {code:""FNT"",city:""Flint"",name:""Bishop International"",country:""USA""},","  {code:""LAN"",city:""Lansing"",name:""Capital Region"",country:""USA""},","  {code:""MBS"",city:""Saginaw"",name:""MBS International"",country:""USA""},","  {code:""AZO"",city:""Kalamazoo"",name:""Kalamazoo Battle Creek"",country:""USA""},","  {code:""TVC"",city:""Traverse City"",name:""Cherry Capital"",country:""USA""},","  {code:""PLN"",city:""Pellston"",name:""Pellston Regional"",country:""USA""},","  {code:""CIU"",city:""Sault Ste. Marie"",name:""Chippewa County"",country:""USA""},","  {code:""ESC"",city:""Escanaba"",name:""Delta County"",country:""USA""},","  {code:""IMT"",city:""Iron Mountain"",name:""Ford Airport"",country:""USA""},","  {code:""APN"",city:""Alpena"",name:""Alpena County Regional"",country:""USA""},","  {code:""CMX"",city:""Hancock"",name:""Houghton County Memorial"",country:""USA""},","  {code:""IWD"",city:""Ironwood"",name:""Gogebic-Iron County"",country:""USA""},","  {code:""MBL"",city:""Manistee"",name:""Manistee County Blacker"",country:""USA""},")
$pb = $NL + ($pi -join $NL)
$c2 = Get-Content $portalFile -Raw
if ($c2 -match "MQT") { Write-Host "[SKIP] Already in portal" -ForegroundColor Yellow } else { $m2 = [regex]::Match($c2, '\{code:"SFO"[^}]+\},?'); if ($m2.Success) { $c2 = $c2.Insert($m2.Index + $m2.Length, $pb); [System.IO.File]::WriteAllText($portalFile, $c2); Write-Host "[OK] Michigan added to portal" -ForegroundColor Green } else { Write-Host "[WARN] SFO not found in portal" -ForegroundColor Red } }
Write-Host "DONE - now run: npx tsx src/scripts/populate.ts" -ForegroundColor Cyan
